let songs = [
    {id:1 , name:'Awaken' , artist: 'League of Legends' , album:'Unknown Album' , src:'src/01 League of Legends - Awaken.mp3' , pic:'img/awaken.jpg'} ,
    {id:2 , name:'Abyss' , artist: 'Yung Blood' , album:'Unknown Album' , src:'src/Abyss.mp3' , pic:'img/abyss.jpg' } ,
    {id:3 , name:'American Cars' , artist: 'Annie' , album:'Unknown Album' , src:'src/Annie_-_American_Cars.mp3' , pic:'img/americancars.jpg' } ,
    {id:4 , name:'Bury' , artist: 'Casey Edwards' , album:'Unknown Album' , src:'src/Bury.mp3' , pic:'img/bury-the-light.jpg' } ,
    {id:5 , name:'Just the right song' , artist: 'Vansire' , album:'Unknown Album' , src:'src/11 - Just the Right Song - Vansire (128).mp3' , pic:'img/vansire.jpg' } ,
    {id:6 , name:'There you are' , artist: 'Unknown' , album:'Unknown Album' , src:'src/There you are.mp3' , pic:'img/UnkownAlbum2.jpg'} ,
    {id:7 , name:'Parandey e Mohajer' , artist: 'Siavash Ghomayshi' , album:'Unknown Album' , src:'src/Siavash Ghomayshi Parandey e Mohajer.mp3' , pic:'img/UnkownAlbum2.jpg' } ,
    {id:8 , name:'Gangnam Style' , artist: 'PSY' , album:'Unknown Album' , src:'src/PSY Gangnam Style.mp3' , pic:'img/Gangnam_Style_Official_Cover.png' } ,
    {id:9 , name:'A Million Roses' , artist: 'Ko Woo Rim' , album:'Unknown Album' , src:'src/ko woo rim a million roses ost my mister part 5.mp3'  , pic:'img/UnkownAlbum.jpg'} ,
    {id:10 , name:'Prisoner' , artist: 'Miley Cyrus' , album:'Unknown Album' , src:'src/Miley Cyrus Prisoner Ft Dua Lipa.mp3' , pic:'img/prisoner.jpg' } ,
    {id:11 , name:'DARK ARIA' , artist: 'Sawano Hiroyuki' , album:'Unknown Album' , src:'src/SawanoHiroyuki[nZk] - DARK ARIA  LV2.mp3' , pic:'img/darkaria.jpg' } ,
    {id:12 , name:'Health' , artist: 'Major Crimes' , album:'Unknown Album' , src:'src/08.“Health” by Major Crimes.mp3' , pic:'img/UnkownAlbum.jpg' } ,
    {id:13 , name:'Only Love' , artist: 'Paloma Faith' , album:'Unknown Album' , src:'src/Paloma Faith - Only Love Can Hurt Like This.mp3' , pic:'img/onlylove.jpg' } ,
    {id:14 , name:'Feel Invincible' , artist: 'Skillet' , album:'Unknown Album' , src:'src/Skillet – Feel Invincible.mp3' , pic:'img/skillet.jpg' } ,
    {id:15 , name:'Invincible' , artist: 'MGK' , album:'Unknown Album' , src:'src/MGK-Invincible-Explicit-ft.-Ester-Dean_147140.mp3' , pic:'img/mgk.jpg' } ,
    {id:16 , name:'Hidden Romance' , artist: 'Atom Music Audio' , album:'Unknown Album' , src:'https://dl6.songsara.net/FRE/11/Atom Music Audio - Hidden Romance (2024) SONGSARA.NET/01 Hidden Romance.mp3' , pic:'img/Hidden.jpg' } ,
    {id:17 , name:'Adelea' , artist: 'Deep House' , album:'Unknown Album' , src:'https://dl6.songsara.net/FRE/11/RILTIM - Adelea (2024) SONGSARA.NET.mp3' , pic:'img/Adelea.jpg' } ,
]